#require 'libxml-jruby'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |s|
    s.name = "libxml-jruby"
    s.summary = "Libxml replacement for JRuby"
    s.email = "uwelk@xhochy.org"
    s.homepage = "http://github.com/xhochy/libxml-jruby"
    s.description = "Lixml replacement for JRuby in 100% Java"
    s.authors = ["Michael Guterl", "Uwe L. Korn"]
    s.files =  FileList["[A-Z]*", "{lib}/**/*"]
    #s.add_dependency ''
  end
rescue LoadError
  puts "Jeweler, or one of its dependencies, is not available. Install it with: sudo gem install technicalpickles-jeweler -s http://gems.github.com"
end

# EOF
